query GetMedia($id: ID!) {
  media(id: $id) {
    id
    title
    description
    mediaType
    duration
    videoPlayerInfo {
      currentTime
      duration
    }
    file {
      name
      name
      mimetype
      encoding
      size
      url
    }
    createdAt
    updatedAt
  }
}
