mutation Create($userId: ID!, $file: Upload!, $category: String!) {
  createFile(input: { userId: $userId, file: $file, category: $category }) {
    id
    url
    path
    size
    contentType
    createdAt
  }
}
