mutation SignIn ($email: String!, $password: String!) {
  signIn(email: $email, password: $password) {
    id
    fullName
    role
    email
    avatarUrl
    token
    tokenExpiredAt
    progress
  }
}
